# Generated by Django 2.2.2 on 2019-06-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
