# Generated by Django 2.2.2 on 2019-06-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_moviedata_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='text',
            new_name='review',
        ),
    ]
