# Generated by Django 2.2.2 on 2019-06-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_auto_20190605_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedata',
            name='image',
        ),
        migrations.RemoveField(
            model_name='moviedata',
            name='link',
        ),
    ]
