# Generated by Django 2.2.2 on 2019-06-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_auto_20190605_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='review',
            field=models.CharField(max_length=500),
        ),
    ]
