# Generated by Django 2.2.2 on 2019-06-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_auto_20190606_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='title',
            field=models.CharField(max_length=200, verbose_name='검색어'),
        ),
    ]
